server:
  port: 8080

user-api:
  url: http://localhost:8081

order-api:
  url : http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: gateway

  endpoint:
    gateway:
      enabled: true